In [2]:
import numpy as np
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [8]:
import numpy as np
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [5]:
#2D Array
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
a.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [6]:
#version
import numpy as np
print(np.__version__)

1.21.5


In [9]:
#converting 1d array to 2d array
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [25]:
#converting 1d array to 3d array
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,1,6)
print(newarr)
print(newarr.ndim)#no of dimensions


[[[ 1  2  3  4  5  6]]

 [[ 7  8  9 10 11 12]]]
3


In [20]:
#onesarray
a=np.ones(5,dtype='int64')
print(a)

[1 1 1 1 1]


In [24]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
x.resize(4,5)#resize
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]


In [27]:
#negative slicing
x=np.array([1,2,3,4,5,6,7])
print(x[-3:-1])
print(x[1:5:2])

[5 6]
[2 4]


In [59]:
#question4
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
print("original array : ",x)
print("size : ",x.size)
x[8]=25
print("array after updating 8th element : ",x)
print("array in reverse order : ",x[::-1])
x1=x.reshape(7,2)
print("reshaped array : ")
print(x1)

original array :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
size :  14
array after updating 8th element :  [ 1  2  3  4  5  6  7  8 25 10 11 12 13 14]
array in reverse order :  [14 13 12 11 10 25  8  7  6  5  4  3  2  1]
reshaped array : 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [25 10]
 [11 12]
 [13 14]]


In [35]:
#question5
x=np.arange(12,32)
x1=x.reshape(5,4)
print("The matrix : ",x1)
print("shape : ",x1.shape)
print("type : ",type(x))
print("data type : ",x.dtype)

The matrix :  [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
shape :  (5, 4)
type :  <class 'numpy.ndarray'>
data type :  int64


In [36]:
#q6

import numpy as np

arr=np.zeros((8,8),dtype=int)
arr[1::2,::2]=1
arr[::2,1::2]=1

print("Checkboard pattern:\n")
print(arr)

Checkboard pattern:

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [37]:
#q7

import numpy as np

arr1=np.array([1,2,3,4])
arr2=np.array([1,4])
print("array 1: ", arr1)
print("array 2: ", arr2)

arr3=np.in1d(arr1,arr2)
print(arr3)

array 1:  [1 2 3 4]
array 2:  [1 4]
[ True False False  True]


In [38]:
#q8

import numpy as np

arr1=np.array([1,2,3,4])
arr2=np.array([5,2,3,7])
print("array 1: ", arr1)
print("array 2: ", arr2)

arr3=np.intersect1d(arr1,arr2)
arr4=np.union1d(arr1,arr2)
print("common elements: ", arr3)
print("union: ", arr4)

array 1:  [1 2 3 4]
array 2:  [5 2 3 7]
common elements:  [2 3]
union:  [1 2 3 4 5 7]


In [39]:
#q9

import numpy as np

arr=np.array([1,2,2,3,4,4,5])

arr2=np.unique(arr)
print("unique elements are: ",arr2)

unique elements are:  [1 2 3 4 5]


In [40]:
#q10

import numpy as np

arr=np.array([1,2,3,4])
print(arr)
print("type:",type(arr))

ls=arr.tolist()
print(ls)
print("type:",type(ls))

[1 2 3 4]
type: <class 'numpy.ndarray'>
[1, 2, 3, 4]
type: <class 'list'>


In [58]:
#pattern 1

import numpy as np

arr=np.zeros((8,8),dtype=int)
arr[::2,::4]=1
arr[::2,1::4]=1

arr[1::2,3::4]=1
arr[1::2,2::4]=1
print("Checkboard pattern:\n")
print(arr)

Checkboard pattern:

[[1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]]


In [45]:
#pattern 2

import numpy as np

arr=np.zeros((8,8),dtype=int)
arr[::2,4::]=1
arr[1::2,:4:]=1

print("Checkboard pattern:\n")
print(arr)

Checkboard pattern:

[[0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]]


In [49]:
#q11

import numpy as np

arr=np.arange(11,21).reshape(5,2)
print("Array is:\n",arr)
print("\n1st column: ",arr[:,0])
print("2nd column: ",arr[:,1])


Array is:
 [[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]

1st column:  [11 13 15 17 19]
2nd column:  [12 14 16 18 20]


In [57]:
#q12

import numpy as np

m1=np.arange(1,10).reshape(3,3)
m2=np.arange(11,20).reshape(3,3)
print("Array 1\n",m1)
print("Array 2\n",m2)

print("\nMultiplied matrix:\n",np.dot(m1,m2))
print("Added matrix:\n",np.add(m1,m2))

Array 1
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 2
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

Multiplied matrix:
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]
Added matrix:
 [[12 14 16]
 [18 20 22]
 [24 26 28]]


In [27]:
#q13

import numpy as np

arr=np.array([[3,1],[2,2]])
print("Array is:\n",arr)

w,v=np.linalg.eig(arr)
print("\nEigen values: ",w)
print("Eigen vectors:\n",v)

Array is:
 [[3 1]
 [2 2]]

Eigen values:  [4. 1.]
Eigen vectors:
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [56]:
#q14

import numpy as np

arr=np.array([[2,3],[4,5]])
print("Original matrix:\n",arr)

print("\nDeterminant:",np.linalg.det(arr))
print("Transpose:\n",np.transpose(arr))
print("Inverse:\n",np.linalg.inv(arr))

Original matrix:
 [[2 3]
 [4 5]]

Determinant: -2.0
Transpose:
 [[2 4]
 [3 5]]
Inverse:
 [[-2.5  1.5]
 [ 2.  -1. ]]


In [35]:
#complex nos

import numpy as np
z = np.array([[1+0.j,2+5.j]])
print(z)
print(z.real)
print(z.imag)

z=np.array([[1,2],[3,4]],dtype=complex)
print("\n",z)

[[1.+0.j 2.+5.j]]
[[1. 2.]]
[[0. 5.]]

 [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [48]:
#file1

import numpy as np
arr = np.arange(1,10)
data = np.array( [[10,20,30], [40,50,60], [70,80,90]] )
np.savetxt('file1.txt',arr,delimiter=",")
np.savetxt('file1.csv',arr,delimiter=",")
np.savetxt('file2.txt',data,delimiter=",")
np.savetxt('file2.csv',data,delimiter=",")

In [46]:
#file2

import numpy as np
np.loadtxt(open("file1.csv","rb"),delimiter=",",dtype=np.int32)

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)